"""initial MVP schema

Revision ID: 17aafec3f9cb
Revises:
Create Date: 2026-06-27 20:09:55.081926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17aafec3f9cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_requests',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('request_type', sa.String(length=60), nullable=False),
    sa.Column('people_affected', sa.Integer(), nullable=False),
    sa.Column('vulnerable_people_present', sa.Boolean(), nullable=False),
    sa.Column('medical_need', sa.Boolean(), nullable=False),
    sa.Column('water_need', sa.Boolean(), nullable=False),
    sa.Column('food_need', sa.Boolean(), nullable=False),
    sa.Column('shelter_need', sa.Boolean(), nullable=False),
    sa.Column('transport_need', sa.Boolean(), nullable=False),
    sa.Column('medical_information_private', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'needs_verification', 'approved', 'rejected', 'duplicate', 'in_progress', 'resolved', 'archived', name='reportstatus', native_enum=False), nullable=False),
    sa.Column('verification_status', sa.Enum('unverified', 'family', 'volunteer', 'organization', 'contradictory', 'needs_information', name='verificationstatus', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='priority', native_enum=False), nullable=False),
    sa.Column('source_channel', sa.Enum('web', 'volunteer', 'phone', 'sms', 'whatsapp', 'paper', 'social', 'organization', 'other', name='sourcechannel', native_enum=False), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('location_text', sa.String(length=160), nullable=False),
    sa.Column('exact_address_private', sa.String(length=240), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_precision', sa.String(length=30), nullable=False),
    sa.Column('description_public', sa.Text(), nullable=False),
    sa.Column('description_private', sa.Text(), nullable=True),
    sa.Column('reporter_name_private', sa.String(length=120), nullable=False),
    sa.Column('reporter_contact_private', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('help_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_help_requests_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_requests_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_requests_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_help_requests_request_type'), ['request_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_requests_source_channel'), ['source_channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_requests_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_requests_verification_status'), ['verification_status'], unique=False)

    op.create_table('location_reports',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('damage_level', sa.String(length=40), nullable=False),
    sa.Column('needs_water', sa.Boolean(), nullable=False),
    sa.Column('needs_food', sa.Boolean(), nullable=False),
    sa.Column('needs_medical', sa.Boolean(), nullable=False),
    sa.Column('needs_shelter', sa.Boolean(), nullable=False),
    sa.Column('needs_transport', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'needs_verification', 'approved', 'rejected', 'duplicate', 'in_progress', 'resolved', 'archived', name='reportstatus', native_enum=False), nullable=False),
    sa.Column('verification_status', sa.Enum('unverified', 'family', 'volunteer', 'organization', 'contradictory', 'needs_information', name='verificationstatus', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='priority', native_enum=False), nullable=False),
    sa.Column('source_channel', sa.Enum('web', 'volunteer', 'phone', 'sms', 'whatsapp', 'paper', 'social', 'organization', 'other', name='sourcechannel', native_enum=False), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('location_text', sa.String(length=160), nullable=False),
    sa.Column('exact_address_private', sa.String(length=240), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_precision', sa.String(length=30), nullable=False),
    sa.Column('description_public', sa.Text(), nullable=False),
    sa.Column('description_private', sa.Text(), nullable=True),
    sa.Column('reporter_name_private', sa.String(length=120), nullable=False),
    sa.Column('reporter_contact_private', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_reports_damage_level'), ['damage_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_reports_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_reports_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_reports_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_location_reports_source_channel'), ['source_channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_reports_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_reports_verification_status'), ['verification_status'], unique=False)

    op.create_table('missing_person_reports',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=40), nullable=True),
    sa.Column('last_contact_date', sa.Date(), nullable=True),
    sa.Column('relationship_to_person_private', sa.String(length=100), nullable=True),
    sa.Column('medical_information_private', sa.Text(), nullable=True),
    sa.Column('involves_minor', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'needs_verification', 'approved', 'rejected', 'duplicate', 'in_progress', 'resolved', 'archived', name='reportstatus', native_enum=False), nullable=False),
    sa.Column('verification_status', sa.Enum('unverified', 'family', 'volunteer', 'organization', 'contradictory', 'needs_information', name='verificationstatus', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='priority', native_enum=False), nullable=False),
    sa.Column('source_channel', sa.Enum('web', 'volunteer', 'phone', 'sms', 'whatsapp', 'paper', 'social', 'organization', 'other', name='sourcechannel', native_enum=False), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('location_text', sa.String(length=160), nullable=False),
    sa.Column('exact_address_private', sa.String(length=240), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_precision', sa.String(length=30), nullable=False),
    sa.Column('description_public', sa.Text(), nullable=False),
    sa.Column('description_private', sa.Text(), nullable=True),
    sa.Column('reporter_name_private', sa.String(length=120), nullable=False),
    sa.Column('reporter_contact_private', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('missing_person_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_missing_person_reports_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_missing_person_reports_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_missing_person_reports_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_missing_person_reports_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_missing_person_reports_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_missing_person_reports_source_channel'), ['source_channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_missing_person_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_missing_person_reports_verification_status'), ['verification_status'], unique=False)

    op.create_table('resource_offers',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('capacity', sa.String(length=120), nullable=True),
    sa.Column('availability', sa.String(length=120), nullable=True),
    sa.Column('public_contact_allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'needs_verification', 'approved', 'rejected', 'duplicate', 'in_progress', 'resolved', 'archived', name='reportstatus', native_enum=False), nullable=False),
    sa.Column('verification_status', sa.Enum('unverified', 'family', 'volunteer', 'organization', 'contradictory', 'needs_information', name='verificationstatus', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='priority', native_enum=False), nullable=False),
    sa.Column('source_channel', sa.Enum('web', 'volunteer', 'phone', 'sms', 'whatsapp', 'paper', 'social', 'organization', 'other', name='sourcechannel', native_enum=False), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('location_text', sa.String(length=160), nullable=False),
    sa.Column('exact_address_private', sa.String(length=240), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_precision', sa.String(length=30), nullable=False),
    sa.Column('description_public', sa.Text(), nullable=False),
    sa.Column('description_private', sa.Text(), nullable=True),
    sa.Column('reporter_name_private', sa.String(length=120), nullable=False),
    sa.Column('reporter_contact_private', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_offers_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_offers_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_offers_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_resource_offers_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_offers_source_channel'), ['source_channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_offers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_offers_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_offers_verification_status'), ['verification_status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'reviewer', 'volunteer', 'viewer', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('abuse_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('missing_person', 'help_request', 'resource_offer', 'location_report', name='reporttype', native_enum=False), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=True),
    sa.Column('submitted_by_contact_private', sa.String(length=160), nullable=True),
    sa.Column('status', sa.Enum('pending', 'reviewed', 'dismissed', 'action_taken', name='abusestatus', native_enum=False), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('abuse_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abuse_reports_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_abuse_reports_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_abuse_reports_status'), ['status'], unique=False)

    op.create_table('admin_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('missing_person', 'help_request', 'resource_offer', 'location_report', name='reporttype', native_enum=False), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_notes_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_notes_report_type'), ['report_type'], unique=False)

    op.create_table('duplicate_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('missing_person', 'help_request', 'resource_offer', 'location_report', name='reporttype', native_enum=False), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('possible_duplicate_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duplicate_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duplicate_candidates_possible_duplicate_id'), ['possible_duplicate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duplicate_candidates_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duplicate_candidates_report_type'), ['report_type'], unique=False)

    op.create_table('report_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('missing_person', 'help_request', 'resource_offer', 'location_report', name='reporttype', native_enum=False), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('pending', 'needs_verification', 'approved', 'rejected', 'duplicate', 'in_progress', 'resolved', 'archived', name='reportstatus', native_enum=False), nullable=False),
    sa.Column('new_status', sa.Enum('pending', 'needs_verification', 'approved', 'rejected', 'duplicate', 'in_progress', 'resolved', 'archived', name='reportstatus', native_enum=False), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_status_history_new_status'), ['new_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_status_history_old_status'), ['old_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_status_history_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_status_history_report_type'), ['report_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_status_history_report_type'))
        batch_op.drop_index(batch_op.f('ix_report_status_history_report_id'))
        batch_op.drop_index(batch_op.f('ix_report_status_history_old_status'))
        batch_op.drop_index(batch_op.f('ix_report_status_history_new_status'))

    op.drop_table('report_status_history')
    with op.batch_alter_table('duplicate_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duplicate_candidates_report_type'))
        batch_op.drop_index(batch_op.f('ix_duplicate_candidates_report_id'))
        batch_op.drop_index(batch_op.f('ix_duplicate_candidates_possible_duplicate_id'))

    op.drop_table('duplicate_candidates')
    with op.batch_alter_table('admin_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_notes_report_type'))
        batch_op.drop_index(batch_op.f('ix_admin_notes_report_id'))

    op.drop_table('admin_notes')
    with op.batch_alter_table('abuse_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abuse_reports_status'))
        batch_op.drop_index(batch_op.f('ix_abuse_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_abuse_reports_report_id'))

    op.drop_table('abuse_reports')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('resource_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_offers_verification_status'))
        batch_op.drop_index(batch_op.f('ix_resource_offers_title'))
        batch_op.drop_index(batch_op.f('ix_resource_offers_status'))
        batch_op.drop_index(batch_op.f('ix_resource_offers_source_channel'))
        batch_op.drop_index(batch_op.f('ix_resource_offers_resource_type'))
        batch_op.drop_index(batch_op.f('ix_resource_offers_public_id'))
        batch_op.drop_index(batch_op.f('ix_resource_offers_priority'))
        batch_op.drop_index(batch_op.f('ix_resource_offers_is_public'))

    op.drop_table('resource_offers')
    with op.batch_alter_table('missing_person_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_missing_person_reports_verification_status'))
        batch_op.drop_index(batch_op.f('ix_missing_person_reports_status'))
        batch_op.drop_index(batch_op.f('ix_missing_person_reports_source_channel'))
        batch_op.drop_index(batch_op.f('ix_missing_person_reports_public_id'))
        batch_op.drop_index(batch_op.f('ix_missing_person_reports_priority'))
        batch_op.drop_index(batch_op.f('ix_missing_person_reports_last_name'))
        batch_op.drop_index(batch_op.f('ix_missing_person_reports_is_public'))
        batch_op.drop_index(batch_op.f('ix_missing_person_reports_first_name'))

    op.drop_table('missing_person_reports')
    with op.batch_alter_table('location_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_reports_verification_status'))
        batch_op.drop_index(batch_op.f('ix_location_reports_title'))
        batch_op.drop_index(batch_op.f('ix_location_reports_status'))
        batch_op.drop_index(batch_op.f('ix_location_reports_source_channel'))
        batch_op.drop_index(batch_op.f('ix_location_reports_public_id'))
        batch_op.drop_index(batch_op.f('ix_location_reports_priority'))
        batch_op.drop_index(batch_op.f('ix_location_reports_is_public'))
        batch_op.drop_index(batch_op.f('ix_location_reports_damage_level'))

    op.drop_table('location_reports')
    with op.batch_alter_table('help_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_help_requests_verification_status'))
        batch_op.drop_index(batch_op.f('ix_help_requests_title'))
        batch_op.drop_index(batch_op.f('ix_help_requests_status'))
        batch_op.drop_index(batch_op.f('ix_help_requests_source_channel'))
        batch_op.drop_index(batch_op.f('ix_help_requests_request_type'))
        batch_op.drop_index(batch_op.f('ix_help_requests_public_id'))
        batch_op.drop_index(batch_op.f('ix_help_requests_priority'))
        batch_op.drop_index(batch_op.f('ix_help_requests_is_public'))

    op.drop_table('help_requests')
    # ### end Alembic commands ###
