"""add pet_records (ingesta verificada)

Revision ID: 274967a07341
Revises: 4d0491ccffc8
Create Date: 2026-06-29 15:25:27.843540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274967a07341'
down_revision = '4d0491ccffc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('source_slug', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('species', sa.String(length=40), nullable=False),
    sa.Column('breed', sa.String(length=120), nullable=True),
    sa.Column('color', sa.String(length=120), nullable=True),
    sa.Column('last_seen_location', sa.String(length=300), nullable=True),
    sa.Column('last_seen_date', sa.Date(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attribution', sa.String(length=240), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_slug', 'external_id', name='uq_pet_records_origin')
    )
    with op.batch_alter_table('pet_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pet_records_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pet_records_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_pet_records_source_slug'), ['source_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_pet_records_species'), ['species'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_records_species'))
        batch_op.drop_index(batch_op.f('ix_pet_records_source_slug'))
        batch_op.drop_index(batch_op.f('ix_pet_records_public_id'))
        batch_op.drop_index(batch_op.f('ix_pet_records_external_id'))

    op.drop_table('pet_records')
    # ### end Alembic commands ###
