"""add lost_pet_reports

Revision ID: 4d0491ccffc8
Revises: c9d0e1f2a3b4
Create Date: 2026-06-29 15:11:14.643060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0491ccffc8'
down_revision = 'c9d0e1f2a3b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lost_pet_reports',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('species', sa.String(length=40), nullable=False),
    sa.Column('breed', sa.String(length=80), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('last_seen_date', sa.Date(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'needs_verification', 'approved', 'rejected', 'duplicate', 'in_progress', 'resolved', 'archived', name='reportstatus', native_enum=False), nullable=False),
    sa.Column('verification_status', sa.Enum('unverified', 'family', 'volunteer', 'organization', 'contradictory', 'needs_information', name='verificationstatus', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='priority', native_enum=False), nullable=False),
    sa.Column('source_channel', sa.Enum('web', 'volunteer', 'phone', 'sms', 'whatsapp', 'paper', 'social', 'organization', 'other', name='sourcechannel', native_enum=False), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('location_text', sa.String(length=160), nullable=False),
    sa.Column('exact_address_private', sa.String(length=240), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_precision', sa.String(length=30), nullable=False),
    sa.Column('description_public', sa.Text(), nullable=False),
    sa.Column('description_private', sa.Text(), nullable=True),
    sa.Column('reporter_name_private', sa.String(length=120), nullable=False),
    sa.Column('reporter_contact_private', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lost_pet_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lost_pet_reports_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_lost_pet_reports_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_lost_pet_reports_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_lost_pet_reports_source_channel'), ['source_channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_lost_pet_reports_species'), ['species'], unique=False)
        batch_op.create_index(batch_op.f('ix_lost_pet_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lost_pet_reports_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_lost_pet_reports_verification_status'), ['verification_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_pet_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lost_pet_reports_verification_status'))
        batch_op.drop_index(batch_op.f('ix_lost_pet_reports_title'))
        batch_op.drop_index(batch_op.f('ix_lost_pet_reports_status'))
        batch_op.drop_index(batch_op.f('ix_lost_pet_reports_species'))
        batch_op.drop_index(batch_op.f('ix_lost_pet_reports_source_channel'))
        batch_op.drop_index(batch_op.f('ix_lost_pet_reports_public_id'))
        batch_op.drop_index(batch_op.f('ix_lost_pet_reports_priority'))
        batch_op.drop_index(batch_op.f('ix_lost_pet_reports_is_public'))

    op.drop_table('lost_pet_reports')
    # ### end Alembic commands ###
