"""add country to recognitions

Revision ID: 9927c9695f15
Revises: d7c2cd32cfbd
Create Date: 2026-06-29 17:32:26.197956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9927c9695f15'
down_revision = 'd7c2cd32cfbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognitions', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
