"""add recognitions

Revision ID: d7c2cd32cfbd
Revises: 274967a07341
Create Date: 2026-06-29 17:14:09.486759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c2cd32cfbd'
down_revision = '274967a07341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recognitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('source_slug', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('org', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attribution', sa.String(length=240), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_slug', 'external_id', name='uq_recognitions_origin')
    )
    with op.batch_alter_table('recognitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recognitions_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recognitions_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_recognitions_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_recognitions_source_slug'), ['source_slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recognitions_source_slug'))
        batch_op.drop_index(batch_op.f('ix_recognitions_public_id'))
        batch_op.drop_index(batch_op.f('ix_recognitions_kind'))
        batch_op.drop_index(batch_op.f('ix_recognitions_external_id'))

    op.drop_table('recognitions')
    # ### end Alembic commands ###
